#!/bin/bash

REPO_ROOT=$(git rev-parse --show-toplevel)
IN=''

while [[ "$#" -gt 0 ]]; do
	case $1 in
		-i|--in) IN="$2"; shift ;;
		-t|--interactive) INTERACTIVE="--interactive"; shift ;;
		*) echo "Unknown parameter passed: $1"; exit 1 ;;
	esac
	shift
done

if [ "$IN" == '' ] && [ "$INTERACTIVE" == '' ]; then
	echo "Error: No command passed, use -i / --in or -t / --interactive."
	exit -1
fi

# docker run : run a command to a container. In this case the '$*' is the complement
#				of the make command of this specific container
# --rm : Delete the container after the exit
# -a <Stream> : Bind the stream of container to the host
# -v <Host Dir>:<Container Dir> : Bind the volume to the container(Both absolute PATHS)
# -e <Var> : Set enviroment variable to the container
# --net=host : Set the container network the same as the host
# --device : bind the host device to the container

docker run --rm -a STDOUT -a STDERR -v $REPO_ROOT:/linux $INTERACTIVE \
	--net=host --name kernel_container linux_dev_tools:1.0 $IN

